### PR TITLE
Change nats-box from Pod to Deployment to fix issue 89

### PR DESCRIPTION
**Pull request by jinq0123**
https://github.com/nats-io/k8s/issues/89
helm: running into issue upgrading nats #89

### CODE REVIEW

**Comment by variadico** [comment]
LGTM!

Although, we need to fix the NOTES.txt file, it's displaying wrong info now.

What helm shows after deploying:
```
NATS Box has been deployed into your cluster, you can
now use the NATS tools within the container as follows:

  kubectl exec -n default -it my-nats-box -- /bin/sh -l

  nats-box:~# nats-sub test &
  nats-box:~# nats-pub test hi
  nats-box:~# nc my-nats 4222

Thanks for using NATS!
```

The pods we actually have:
```
$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
my-nats-box-6f59bdf57c-gjdxh   1/1     Running   0          2m54s
my-nats-0                      3/3     Running   0          2m54s
```

It would be nice if the notes showed the correct command.
```
kubectl exec -n default -it my-nats-box-6f59bdf57c-gjdxh -- /bin/sh -l
```

**Comment by wallyqs** [comment]
Maybe can use something like
```
kubectl exec -it deployment/my-nats-box -- /bin/sh -l
```

**Comment by greg-md** [comment]
I am still getting the same issue. Did you forget to create a new helm version? https://artifacthub.io/packages/helm/nats/nats

**Comment by wallyqs** [comment]
@greg-md yes we haven't made the release yet, likely a release this week

**Pull request merged**
