### PR TITLE
Sidecar leafnode certificates

### PR DESCRIPTION
**Pull request by chris13524**
This PR makes it possible to:
- provide additional containers, volumes, and volume mounts to the statefulset
- provide custom leafnodes TLS configuration options
- provide extra configuration to the reloader sidecar

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM!

**Comment by chris13524** [comment]
Is this planning to be merged soon?

**Comment by wallyqs** [comment]
Merged, thanks again!

**Comment by TheQueenIsDead** [comment]
It's a shame lint tests aren't ran on feature branches, seems as though this might have broken the build @chris13524 :
https://github.com/nats-io/k8s/actions

Is the best way to rectify this to run a build on either your fork or mine, and attempt to get it to pass, or might we be able to use chart-testing (ct lint) locally? Not sure if specific config is required to get that going.'

At work at the moment, but could have a look afterwards

**Comment by TheQueenIsDead** [comment]
Hmm, super interesting, running the tests at home against a minikube instance yielded fine results
```
~/go/src/github.com/TheQueenIsDead/k8s$ ./ct install --all --chart-dirs helm/charts --excluded-charts nats-account-server,nats-kafka,surveyor
...
------------------------------------------------------------------------------------------------------------------------
 ✔︎ nack => (version: "0.9.2", path: "helm/charts/nack")
 ✔︎ nats => (version: "0.10.0", path: "helm/charts/nats")
 ✔︎ nats-operator => (version: "0.7.4", path: "helm/charts/nats-operator")
 ✔︎ stan => (version: "0.10.0", path: "helm/charts/stan")
------------------------------------------------------------------------------------------------------------------------
All charts installed successfully
```

**Comment by chris13524** [comment]
@TheQueenIsDead thanks for finding this! Looks like I forgot to test the install using default values. I created #388 that should fix this.

**Comment by chris13524** [comment]
Can we update the actions to use [`on: pull_request`](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request)?

**Comment by TheQueenIsDead** [comment]
Champion, thanks for fixing it! Good call just running an install to debug it, the ct test output was pretty verbose and unfamiliar to me

**Pull request merged**
