### PR TITLE
Add nack accounts

### PR DESCRIPTION
**Pull request by variadico**
This adds NACK Accounts to the JetStream Controller. Other half of https://github.com/nats-io/nack/pull/42

### CODE REVIEW

**Comment by sergeyshaykhullin** [comment]
@wallyqs Why do we have multiple places with CRDs?

1. k8s repo https://github.com/nats-io/k8s/blob/main/nack/crds.yml
2. NACK repo https://github.com/nats-io/nack/blob/main/deploy/crds.yml

That is the preferred file to follow?

**Comment by wallyqs** [comment]
both are the same, but good point maybe should just keep the one in the nack repo.

**Comment by sergeyshaykhullin** [comment]
Yes, right now they are the same, but not in a future)

**Comment by wallyqs** [comment]
ok removed from the k8s repo and should be single copy in nack now

**Pull request merged**
